# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- projet-devops-azure

pool:
  #name: Default
  vmImage: 'ubuntu-latest'

steps:

# 1 Checkout du code
- checkout: self
  clean: true
  persistCredentials: true
  
# 2 Vérifier l'existence de package.json
- script: |
    if [ ! -f "$(Build.SourcesDirectory)/angular-app-kubernetes/package.json" ]; then
      echo "Erreur :package.json introuvable !"
      exit 1
    fi
  displayName: "Vérifier l'existence de package.json"

# 3 Installer Node.js 20
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Use Node.js 20'

# 4 Installer Angular CLI et les dépendances du projet
- script: |
    echo "Installation de Angular CLI et des dépendances"
    cd $(Build.SourcesDirectory)/angular-app-kubernetes
    npm install -g @angular/cli@16 
    npm install 
    ng version 
  displayName: 'Install Angular CLI and dependencies'

# 5 Préparer l’analyse SonarCloud
- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'SonarCloudServiceConnection'
    organization: 'hanennaoua'
    projectKey: 'hanennaoua_DEVOPS-AZURE'
    projectName: 'DEVOPS-AZURE'
    scannerMode: 'CLI'
    extraProperties: |
      sonar.projectKey=hanennaoua_DEVOPS-AZURE
      sonar.organization=hanennaoua
      sonar.host.url=https://sonarcloud.io
      sonar.sources=

# 6 Build du projet Angular
- script: |
    echo "Build du frontend en mode production"
    cd $(Build.SourcesDirectory)/angular-app-kubernetes
    npm run build -- --configuration=production
  displayName: 'Build Angular Project'

# 7 Exécuter l'analyse SonarCloud
- task: SonarCloudAnalyze@3
  displayName: 'Run SonarCloud Analysis'