trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'  # Ou 'windows-latest' si besoin

steps:
  - checkout: self

  - script: |
      if [ ! -f "angular-app-kubernetes/package.json" ]; then
        echo "Erreur : package.json introuvable !"
        exit 1
      fi
    displayName: "Vérifier package.json"

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli@16
      npm ci
      ng build --configuration production
    displayName: "Build Angular"
    workingDirectory: 'angular-app-kubernetes'

  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      repository: 'hanen90/devops-azure'
      tags: |
        latest
        $(Build.BuildId)
      Dockerfile: 'angular-app-kubernetes/Dockerfile'